if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/numeric/numeric_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/numeric/numeric_tests[1]_tests.cmake")
else()
  add_test(numeric_tests_NOT_BUILT numeric_tests_NOT_BUILT)
endif()
