if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/commitment/pedersen/stdlib_pedersen_commitment_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/commitment/pedersen/stdlib_pedersen_commitment_tests[1]_tests.cmake")
else()
  add_test(stdlib_pedersen_commitment_tests_NOT_BUILT stdlib_pedersen_commitment_tests_NOT_BUILT)
endif()
