if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/stdlib_circuit_builders_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib_circuit_builders/stdlib_circuit_builders_tests[1]_tests.cmake")
else()
  add_test(stdlib_circuit_builders_tests_NOT_BUILT stdlib_circuit_builders_tests_NOT_BUILT)
endif()
