if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/vm/vm_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/vm/vm_tests[1]_tests.cmake")
else()
  add_test(vm_tests_NOT_BUILT vm_tests_NOT_BUILT)
endif()
