if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/crypto/aes128/crypto_aes128_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/crypto/aes128/crypto_aes128_tests[1]_tests.cmake")
else()
  add_test(crypto_aes128_tests_NOT_BUILT crypto_aes128_tests_NOT_BUILT)
endif()
