if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/crypto/sha256/crypto_sha256_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/crypto/sha256/crypto_sha256_tests[1]_tests.cmake")
else()
  add_test(crypto_sha256_tests_NOT_BUILT crypto_sha256_tests_NOT_BUILT)
endif()
