if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/plonk/plonk_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/plonk/plonk_tests[1]_tests.cmake")
else()
  add_test(plonk_tests_NOT_BUILT plonk_tests_NOT_BUILT)
endif()
