if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/crypto/generators/crypto_generator_data_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/crypto/generators/crypto_generator_data_tests[1]_tests.cmake")
else()
  add_test(crypto_generator_data_tests_NOT_BUILT crypto_generator_data_tests_NOT_BUILT)
endif()
