if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/crypto/poseidon2/crypto_poseidon2_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/crypto/poseidon2/crypto_poseidon2_tests[1]_tests.cmake")
else()
  add_test(crypto_poseidon2_tests_NOT_BUILT crypto_poseidon2_tests_NOT_BUILT)
endif()
