if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/hash/poseidon2/stdlib_poseidon2_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/hash/poseidon2/stdlib_poseidon2_tests[1]_tests.cmake")
else()
  add_test(stdlib_poseidon2_tests_NOT_BUILT stdlib_poseidon2_tests_NOT_BUILT)
endif()
