if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/examples/join_split/join_split_example_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/examples/join_split/join_split_example_tests[1]_tests.cmake")
else()
  add_test(join_split_example_tests_NOT_BUILT join_split_example_tests_NOT_BUILT)
endif()
