if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/crypto/pedersen_hash/crypto_pedersen_hash_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/crypto/pedersen_hash/crypto_pedersen_hash_tests[1]_tests.cmake")
else()
  add_test(crypto_pedersen_hash_tests_NOT_BUILT crypto_pedersen_hash_tests_NOT_BUILT)
endif()
