if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/circuit_checker/circuit_checker_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/circuit_checker/circuit_checker_tests[1]_tests.cmake")
else()
  add_test(circuit_checker_tests_NOT_BUILT circuit_checker_tests_NOT_BUILT)
endif()
