if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/encryption/schnorr/stdlib_schnorr_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/encryption/schnorr/stdlib_schnorr_tests[1]_tests.cmake")
else()
  add_test(stdlib_schnorr_tests_NOT_BUILT stdlib_schnorr_tests_NOT_BUILT)
endif()
