if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/ultra_honk/ultra_honk_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/ultra_honk/ultra_honk_tests[1]_tests.cmake")
else()
  add_test(ultra_honk_tests_NOT_BUILT ultra_honk_tests_NOT_BUILT)
endif()
