if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/hash/sha256/stdlib_sha256_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/hash/sha256/stdlib_sha256_tests[1]_tests.cmake")
else()
  add_test(stdlib_sha256_tests_NOT_BUILT stdlib_sha256_tests_NOT_BUILT)
endif()
