if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/hash/blake2s/stdlib_blake2s_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/hash/blake2s/stdlib_blake2s_tests[1]_tests.cmake")
else()
  add_test(stdlib_blake2s_tests_NOT_BUILT stdlib_blake2s_tests_NOT_BUILT)
endif()
