if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/goblin/goblin_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/goblin/goblin_tests[1]_tests.cmake")
else()
  add_test(goblin_tests_NOT_BUILT goblin_tests_NOT_BUILT)
endif()
