# CMake generated Testfile for 
# Source directory: /Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src
# Build directory: /Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("barretenberg/bb")
subdirs("barretenberg/circuit_checker")
subdirs("barretenberg/client_ivc")
subdirs("barretenberg/commitment_schemes")
subdirs("barretenberg/common")
subdirs("barretenberg/crypto")
subdirs("barretenberg/dsl")
subdirs("barretenberg/ecc")
subdirs("barretenberg/eccvm")
subdirs("barretenberg/eccvm_recursion")
subdirs("barretenberg/env")
subdirs("barretenberg/execution_trace")
subdirs("barretenberg/examples")
subdirs("barretenberg/flavor")
subdirs("barretenberg/goblin")
subdirs("barretenberg/grumpkin_srs_gen")
subdirs("barretenberg/honk")
subdirs("barretenberg/numeric")
subdirs("barretenberg/plonk")
subdirs("barretenberg/plonk_honk_shared")
subdirs("barretenberg/polynomials")
subdirs("barretenberg/protogalaxy")
subdirs("barretenberg/relations")
subdirs("barretenberg/serialize")
subdirs("barretenberg/solidity_helpers")
subdirs("barretenberg/srs")
subdirs("barretenberg/stdlib")
subdirs("barretenberg/stdlib_circuit_builders")
subdirs("barretenberg/sumcheck")
subdirs("barretenberg/transcript")
subdirs("barretenberg/translator_vm")
subdirs("barretenberg/translator_vm_recursion")
subdirs("barretenberg/ultra_honk")
subdirs("barretenberg/vm")
subdirs("barretenberg/wasi")
subdirs("barretenberg/benchmark")
