if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/plonk_recursion/stdlib_plonk_recursion_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/plonk_recursion/stdlib_plonk_recursion_tests[1]_tests.cmake")
else()
  add_test(stdlib_plonk_recursion_tests_NOT_BUILT stdlib_plonk_recursion_tests_NOT_BUILT)
endif()
