if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/ecc/ecc_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/ecc/ecc_tests[1]_tests.cmake")
else()
  add_test(ecc_tests_NOT_BUILT ecc_tests_NOT_BUILT)
endif()
