if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/sumcheck/sumcheck_tests[1]_tests.cmake")
else()
  add_test(sumcheck_tests_NOT_BUILT sumcheck_tests_NOT_BUILT)
endif()
