if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/primitives/stdlib_primitives_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/stdlib/primitives/stdlib_primitives_tests[1]_tests.cmake")
else()
  add_test(stdlib_primitives_tests_NOT_BUILT stdlib_primitives_tests_NOT_BUILT)
endif()
