if(EXISTS "/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/eccvm/eccvm_tests[1]_tests.cmake")
  include("/Users/harjasleenmalvai/Documents/phdProjects/parsing_proofs/aztec-packages/barretenberg/cpp/src/barretenberg/eccvm/eccvm_tests[1]_tests.cmake")
else()
  add_test(eccvm_tests_NOT_BUILT eccvm_tests_NOT_BUILT)
endif()
